config/routes.rb
Rails.application.routes.draw do
  get 'ptt/index' => 'ptt#index'
  get 'ptt/search' => 'ptt#search'
  get 'ptt/delete' => 'ptt#delete'
  root 'ptt#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/origin_number.rb
class OriginNumber < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ptt_controller.rb
class PttController < ApplicationController
require "open-uri"
require "nokogiri"
require "uri"
require 'erb'
  
  def index


  end
  
  $name=""
  def search 
    @board=params[:search]
    @keyword = params[:keyword]
    if @board!=$name   #initial database
      Article.delete_all
      $name = @board
      OriginNumber.delete_all
      $originCount = 0
      $diff = 0
    end 
    @main = Nokogiri::HTML(open("https://www.ptt.cc/bbs/#{@board}/index.html"))
    @main.css(".r-ent").each do |m|
      if m.css('div.title a').map{ |link| link['href']}.join(",")==""
        next
      end
      if !m.at_css(".title > a").text.include? "#{@keyword}"
        next
      end
      hrefpart = m.css('div.title a').map{ |link| link['href']}.join(",")
      href = "https://www.ptt.cc"+ hrefpart
      if !Article.exists?(href:"#{href}")
        @articles = Article.create(:name => m.at_css(".title > a").text , :href => href )
      end
      

    end    
    $all = Article.all
      if OriginNumber.first.nil?
        OriginNumber.create(:number => $all.count)
        $originCount = OriginNumber.first.number
      end
      $diff = Article.count - $originCount


    respond_to do |format|
            format.js
    end  
  end
  
  def delete
    Article.delete_all
    OriginNumber.delete_all
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ptt_helper.rb
module PttHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PTT爬爬樂</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/ptt/_search.html.erb
<%#=<% @main.css(".r-ent").each do |m| %>
<%#=       <%= m.at_css(".title > a").text %>
<%#=    <p></p>
<%#=<% end %>   
<% if !$all.nil? %>
    <% $all.each_with_index do |article,i|%>
        <% if i < $originCount %>
            <% next %>
        <% end %>
        <%= link_to article.name, "#{article.href}", target: "_blank" %>
        <hr>
    <% end %>
<% end %>

<script>
    var diff=<%= $diff %>;
    if(diff!=0)
        document.title = "PTT爬爬樂"+"("+diff+")";
</script>

app/views/ptt/delete.html.erb
<p>try</p>

app/views/ptt/index.html.erb
<%#=<% @main.css(".r-ent").each do |m| %>
<%#=       <%= m.at_css(".title > a").text %>
<%#=    <p></p>
<%#=<% end %>    
<h1>PTT 爬爬樂</h1>

<%= form_tag ptt_search_path, :method => 'get' , remote: true  do %>
<div class="col-lg-6">
  <div class="input-group">
      <div class="text_field">
        <%= text_field_tag :search ,params[:search] , class:"form-control", placeholder:"輸入看板名",autofocus: "true"%>
        <%= text_field_tag :keyword ,params[:keyword] , class:"form-control", placeholder:"輸入關鍵字",autofocus: "true"%>
      </div>
        <%#<%= hidden_field_tag :page, params[:page]=1 %> <%#傳送初始頁碼 %>
        <%#<%= hidden_field_tag :view, params[:view]=1 %>
    <span class="input-group-btn">
        <%= submit_tag "Search", class:"btn btn-default", id:"button1"%>
        <%= submit_tag "stop" ,class:"btn btn-default", id:"stop" , type: "button"%>
        <%= submit_tag "Search", class:"btn btn-default", id:"button", style:"display:none"%>
    </span>
  </div>
</div>
<% end %>
<p>
<span id = 'result'>
    <% render 'ptt/search' %>
</span>

<script>
        var interval;
        document.getElementById("button1").onclick=function(){
            $("#button").click();
            document.getElementById("button1").setAttribute("disabled", "disabled");
                interval = setInterval(function(){ 
                $("#button").click();
                var originalTitle = document.title;
                    },3000);
        }
        document.getElementById("stop").onclick=function(){
                clearInterval(interval);
                document.getElementById("button1").removeAttribute("disabled");
                document.title = "PTT爬爬樂";
        }
         
        
</script>

app/views/ptt/search.js.erb
$("#result").html("<%= j render partial: 'search'  %>");